config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  resources :users
  resources :sessions, only: [:create] # 9行目と10行目が存在するから、:newや:logoutは必要ない(なくてもエラーは出ないけど、たくさんルーツがでて見づらい)
  resources :categories
  resources :answers
  resources :relationships

  namespace :admin do #namespaceはフォルダを指定,  categoriesはたくさんのwordsを持っているからcateogriesの中に書く
    resources :categories do
      resources :words
    end

    resources :users
  end

  resources :lessons do #lessonsはいくつものanswersを持つ
    resources :answers
  end

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # resources :usersと入力した瞬間に、new.htmlに飛べるようになる。
  # その上で、5行目は、URLを/signupと設定し、そこに飛ばすとusers#newというページにリンクするというカスタマイズ
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length:{ minimum: 6 }
  mount_uploader :avatar, AvatarUploader
  
  has_many :lessons

  def took_lesson(category)
    lessons.find_by(category: category)
  end

  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key:"followed_id",dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :activities

  def follow(user)
    active_relationships.create(followed: user)
  end

  def unfollow(user)
    active_relationships.find_by(followed: user).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin

  def index
    @users = User.paginate(page: params[:page], per_page:10)
  end

  def update #add user as admin
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin, true)

    redirect_to admin_users_url
  end

  def destroy #remove user as admin
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin, false)

    redirect_to admin_users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #サインアップページ
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page:10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.order(created_at: :desc).paginate(page: params[:page],per_page:6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% if user != current_user %>
    <% if current_user.following?(user) %>
        <%= button_to "Unfollow", relationship_path(current_user.active_relationships.find_by(followed: user)), method: :delete, class: "btn btn-primary float-right mt-2" %>
    <% else %>
        <%= button_to "Follow", relationships_path, params: {followed_id: user.id}, class: "btn btn-primary float-right mt-2" %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%=form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>

    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control"%>

    <%= f.label :password %>
    <%= f.text_field :password, class: "form-control"%>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.text_field :password_confirmation, class: "form-control"%>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>

    <br>

    <%= f.submit "SUBMIT", class: "btn btn-block btn-primary" %>
<% end %>

app/views/users/dashboard.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-4 left-box">
            <div class="card mb-4 pt-4">
                <% if current_user.avatar.url != nil %>
                   <%= image_tag current_user.avatar.url, class:"rounded-circle iconpic", size: 150 %>
                <% else %>
                    <%= image_tag "default.JPG", class:"rounded-circle iconpic", size: 150 %>
                <% end %>
                <div class="card-body text-center">
                    <h5 class="card-title"><%= current_user.name %></h5>
                    <p class="card-text"><%= current_user.email %></p>
                    <%= link_to "View Profile", current_user, class:"btn btn-primary" %>
                    <%= link_to "Update Profile", edit_user_path(current_user), class:"btn btn-info" %>
                </div>
            </div>
            <div class="card text-center mb-4 p-4">
                <%= current_user.following.count %> following
                <%= current_user.followers.count %> followers
            </div>
            <div class="card p-4">
                <div class="bg-info text-center">
                words learned
                </div>
            </div>
        </div>

        <div class="col-8 right-box">
            <div class="card">
                <div class="bg-info p-1 mb-1">
                Activity feed
                </div>
                <% @activities.each do |activity| %>
                    <div class="media mb-1">
                        <% if activity.user.avatar %>
                            <%= image_tag activity.user.avatar.url, class: "mr-3", size:60 %>
                        <% else %>
                            <%= image_tag "default.JPG", class:"mr-3 useravatar", size:60 %>
                        <% end %>
                        <div class="media-body p-1">
                            <h5 class="mt-0">
                                <%= link_to current_user == activity.user ? "YOU" : activity.user.name, activity.user %>
                                <% if activity.action_type == "Relationship" %>
                                    followed <%= activity.action.followed.name %>
                                <% else %>
                                    learned <%= activity.action.result %> of <%= activity.action.words.count %> in <%= link_to activity.action.category.title, activity.action %>
                                <% end %>
                            </h5>
                            <small class="text-muted">
                                <% time_ago_in_words(activity.created_at) %>
                            </small>
                        </div>
                    </div>
                <% end %>
                <div class="bg-info p-1" style="height:16px">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="edit_bg">
    <br>
    <div class="jumbotron w-50 ">
        <h1 class="text-center">Sign Up</h1>
        <div class="container">
            <%= render 'form' %><!--パーシャルファイルの_formから引っ張ってきて表示-->
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users')%>
<div class="container">
    <h1 class="text-center">List of Users</h1>
    <br>
    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
    <div class="row justify-content-around">
            <% @users.each do |user| %>
                <div class="col-md-5 each_user_box mb-3 p-3">
                    <% if user.avatar.url != nil %>
                        <%= image_tag user.avatar.url, class:"mr-2 useravatar", size:60%>
                        <%= link_to user.name, user%>
                        <%= render "follow_form",user: user%>
                    <% else %>
                        <%= image_tag "default.JPG", class:"mr-2 useravatar", size:60%>
                        <%= link_to user.name, user%>
                        <%= render "follow_form",user: user%>
                    <% end %>
                </div>
            <% end %>
    </div>
    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
<!--もともとUsers#newだったところ-->
<div class="signup_bg">
    <br>
    <div class="jumbotron w-50 ">
        <h1 class="text-center">Sign Up</h1>
        <div class="container">
            <%= render 'users/form' %><!--パーシャルファイルの_formから引っ張ってきて表示-->
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-4 left-box">
            <div class="card mb-4 pt-4">
                <% if current_user.avatar.url != nil %>
                   <%= image_tag current_user.avatar.url, class:"rounded-circle iconpic", size: 150 %>
                <% else %>
                    <%= image_tag "default.JPG", class:"rounded-circle iconpic", size: 150 %>
                <% end %>
                <div class="card-body text-center">
                    <h5 class="card-title"><%= current_user.name %></h5>
                    <p class="card-text"><%= current_user.email %></p>
                </div>
            </div>
            <div class="card text-center mb-4 p-4">
                <%= current_user.following.count %> following
                <%= current_user.followers.count %> followers
            </div>
            <div class="card p-4">
                <div class="bg-info text-center">
                words learned
                </div>
            </div>
        </div>

        <div class="col-8 right-box">
            <div class="card">
                <div class="bg-info p-1 mb-1">
                Activity feed
                </div>
                <% @activities.each do |activity| %>
                    <div class="media mb-1">
                        <% if activity.user.avatar %>
                            <%= image_tag activity.user.avatar.url, class: "mr-3", size:60 %>
                        <% else %>
                            <%= image_tag "default.JPG", class:"mr-3 useravatar", size:60 %>
                        <% end %>
                        <div class="media-body p-1">
                            <h5 class="mt-0">
                                <%= link_to current_user == activity.user ? "YOU" : activity.user.name, activity.user %>
                                <% if activity.action_type == "Relationship" %>
                                    followed <%= activity.action.followed.name %>
                                <% else %>
                                    learned <%= activity.action.result %> of <%= activity.action.words.count %> in <%= link_to activity.action.category.title, activity.action %>
                                <% end %>
                            </h5>
                            <small class="text-muted">
                                <% time_ago_in_words(activity.created_at) %>
                            </small>
                        </div>
                    </div>
                <% end %>
                <div class="bg-info p-1" style="height:16px">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>