config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  resources :users
  resources :sessions, only: [:create] # 9行目と10行目が存在するから、:newや:logoutは必要ない(なくてもエラーは出ないけど、たくさんルーツがでて見づらい)
  resources :categories
  resources :answers
  resources :relationships

  namespace :admin do #namespaceはフォルダを指定,  categoriesはたくさんのwordsを持っているからcateogriesの中に書く
    resources :categories do
      resources :words
    end

    resources :users
  end

  resources :lessons do #lessonsはいくつものanswersを持つ
    resources :answers
  end

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # resources :usersと入力した瞬間に、new.htmlに飛べるようになる。
  # その上で、5行目は、URLを/signupと設定し、そこに飛ばすとusers#newというページにリンクするというカスタマイズ
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words #カテゴリは複数のwordsを持つ
  has_many :lessons
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_admin

  def new
    @category = Category.new
  end

  def index
    #@categories = Category.all 全部表示させる
    @categories = Category.paginate(page: params[:page], per_page:5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @words = @category.words
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="admin_new_bg">
    <br>
    <div class="container new_edit_container w-50">
        <br>
        <h1 class="text-center">Edit Category</h1>
        <%= form_for([:admin,@category]) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>

            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control des_form" %>

            <br>

            <%= f.submit "SAVE CHANGES", class: "btn btn-block btn-primary" %>
        <% end %>
        <br>
    </div>
    <br>
    <div>
        <%= link_to "＜＜　Back to Index", admin_categories_path, class: "text-white" %>
    </div>
<div>

app/views/admin/categories/index.html.erb
<div class="index_bg">
    <br>
    <div class="index_box text-center">
        <br>
        <h1 class="admin_title">Administer Categories</h1><!--Administer = 管理する-->
        <%= link_to "New Category", new_admin_category_path, class: "btn bg-info btn-lg btn-block text-white" %>
    </div>

    <br>

    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
    <div class="index_category_table">
        <table>
            <thead>
                <tr>
                    <td>Title</td>
                    <td>Description</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.title %></td>
                        <td><%= category.description %></td>
                        <td>
                            <%= link_to "Add word", admin_category_path(category)%>/
                            <%= link_to "Edit", edit_admin_category_path(category) %>/
                            <%= link_to "Delete", admin_category_path(category), method: :delete %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <br>
    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="admin_new_bg">
    <br>
    <div class="container new_edit_container w-50">
        <h1 class="text-center">New Category</h1>
        <%= form_for(:category, url: admin_categories_path) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>

            <%= f.label :description %>
            <%= f.text_field :description, class: "form-control des_form" %>

            <br>

            <%= f.submit "SUBMIT", class: "btn btn-block btn-primary" %>
        <% end %>
    </div>
<div>

app/views/admin/categories/show.html.erb
<div class="word_bg">
    <br>
    <div class="word_box text-center">
        <br>
        <h1 class="word_title"><%= @category[:title] %></h1>
        <%= link_to "New Word", new_admin_category_word_path(@category), class: "btn bg-info btn-lg btn-block text-white" %>
    </div>

    <br>

    <div class="words_show_table">
        <table>
            <thead>
                <tr>
                    <td>Word</td>
                    <td>Answer</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody>
                <% @words.each do |word| %>
                    <tr>
                        <td><%= word.content %></td>
                        <td><%= word.correct_answer %></td>
                        <td>
                            <%= link_to "Edit", edit_admin_category_word_path(@category, word) %>/
                            <%= link_to "Delete", admin_category_word_path(@category, word), method: :delete %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div>
        <%= link_to "＜＜　Back to Index", admin_categories_path, class: "text-white" %>
    </div>
    
    <br>

</div>