config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  resources :users
  resources :sessions, only: [:create] # 9行目と10行目が存在するから、:newや:logoutは必要ない(なくてもエラーは出ないけど、たくさんルーツがでて見づらい)
  resources :categories
  resources :answers
  resources :relationships

  namespace :admin do #namespaceはフォルダを指定,  categoriesはたくさんのwordsを持っているからcateogriesの中に書く
    resources :categories do
      resources :words
    end

    resources :users
  end

  resources :lessons do #lessonsはいくつものanswersを持つ
    resources :answers
  end

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # resources :usersと入力した瞬間に、new.htmlに飛べるようになる。
  # その上で、5行目は、URLを/signupと設定し、そこに飛ばすとusers#newというページにリンクするというカスタマイズ
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words #カテゴリは複数のwordsを持つ
  has_many :lessons
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_admin

  def new
    @category = Category.new
  end

  def index
    #@categories = Category.all 全部表示させる
    @categories = Category.paginate(page: params[:page], per_page:5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @words = @category.words
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="container mt-5 lesson-container">
    <div class="row">
        <% @categories.each do |category| %>
            <div class="col-6">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title"><%= category.title %></h5><!--カテゴリ名-->
                        <p class="card-text"><%= category.description %></p><!--description　説明文-->
                        <% @lesson = current_user.took_lesson(category) %>
                        <% if @lesson.nil? %>
                            <%= button_to "Start Lesson",lessons_path(category_id: category.id), class: "btn btn-primary float-right"%>
                        <% else %>
                            <%= link_to "Show Result", lesson_path(@lesson), class: "btn btn-light float-right" %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="paginate text-center">
        <%= will_paginate %>
    </div>
</div>