config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  resources :users
  resources :sessions, only: [:create] # 9行目と10行目が存在するから、:newや:logoutは必要ない(なくてもエラーは出ないけど、たくさんルーツがでて見づらい)
  resources :categories
  resources :answers
  resources :relationships

  namespace :admin do #namespaceはフォルダを指定,  categoriesはたくさんのwordsを持っているからcateogriesの中に書く
    resources :categories do
      resources :words
    end

    resources :users
  end

  resources :lessons do #lessonsはいくつものanswersを持つ
    resources :answers
  end

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # resources :usersと入力した瞬間に、new.htmlに飛べるようになる。
  # その上で、5行目は、URLを/signupと設定し、そこに飛ばすとusers#newというページにリンクするというカスタマイズ
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :action, polymorphic: true
  belongs_to :user
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words #カテゴリは複数のwordsを持つ
  has_many :lessons
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word #choicesはwordにひもづく
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many :words, through: :answers
  has_many :choices, through: :answers

  has_one :activity, as: :action, dependent: :destroy

  def next_word
    (category.words - words).first
  end

  def lesson_results
    choices.where(is_correct: true).count
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  has_one :activity, as: :action, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length:{ minimum: 6 }
  mount_uploader :avatar, AvatarUploader
  
  has_many :lessons

  def took_lesson(category)
    lessons.find_by(category: category)
  end

  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key:"followed_id",dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :activities

  def follow(user)
    active_relationships.create(followed: user)
  end

  def unfollow(user)
    active_relationships.find_by(followed: user).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category #ワードはカテゴリに紐づく
  has_many :choices, dependent: :destroy #ワードは複数のchoicesを持つ
  accepts_nested_attributes_for :choices

  validates :content, presence: true
  validates :choices, presence: true
  validate :has_one_correct
  validate :has_unique_choices

  def correct_answer
    choices.find_by(is_correct: true).content
  end

  private
    def has_one_correct
      if choices.select {|choice| choice.is_correct == true }.count !=1
        return errors.add :base,"Must have one correct choice"
      end
    end

    def has_unique_choices
      if choices.uniq {|choice| choice.content }.count < choices.length
        return errors.add :base, "Must have unique choices"
      end
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new  #check if all words are answered
    @answer = Answer.new
    @lesson = Lesson.find(params[:lesson_id])

    if @lesson.next_word.nil? #after the last word is finished, return to XXX page
      @lesson.update(result: @lesson.lesson_results) #lessonsテーブルのresultだけを編集するから
      @lesson.create_activity(user: current_user)
      redirect_to lesson_url(@lesson) #in show page: @lesson.result
    end
  end

  def create #Save answer
    @lesson = Lesson.find(params[:lesson_id])
    @lesson.answers.create(answer_params)
    redirect_to new_lesson_answer_url(@lesson)
  end

  private
  def answer_params
    params.require(:answer).permit(:word_id,:choice_id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def create #index.htmlのstart learnボタンをおした時に飛ぶところを指定
    @category = Category.find(params[:category_id])#lessonはcategoryに紐づくから、先にカテゴリを書く
    @lesson = @category.lessons.create(user: current_user)
    redirect_to new_lesson_answer_url(@lesson) #←new_lesson_answer_urlでanswerscontrollerのnewメソッドへ飛ぶ
  end

  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #サインアップページ
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page:10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.order(created_at: :desc).paginate(page: params[:page],per_page:6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #入力されたユーザーのidを探し出しログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  #現在ログインしているユーザーがいる場合、ユーザーを復元？
  def current_user
    if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
        # @current_user = @current_user || User.find_by(id: session[:user_id])
    end
  end

  #ユーザーがログインしているかどうかを判別する機能があります
  def logged_in?
    !current_user.nil?
    # current_user.nil?
    # 入っていると　= false
    # 入ってないと  = true
    # !current_user.nil?
    # 入っていると　= true
    # 入ってないと  = false
  end

  #ログアウト＝delete
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  #現在のlogin_inユーザーを返し、
  #Returns trueは、指定されたユーザーが現在のユーザーである場合
  def current_user?(user)
    user == current_user
  end
  #ログインしていないユーザーがマイクロポストを作らないようにするため
  def only_loggedin_users
    redirect_to login_url unless logged_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer navbar-expand-lg fixed-bottom navbar-dark bg-info pt-3">
    <p class="text-center text-light">&copy Ayaka.inc</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <a class="navbar-brand" href="/">Elearing</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <% if logged_in? %>
                <li><%= link_to "Dashboard", root_path, class: "nav-link"%></li>
                <li><%= link_to "Users", users_path, class: "nav-link"%></li>
                <li><%= link_to "Lessons", categories_path, class: "nav-link"%></li>
                <li><%= link_to "members", users_path, class: "nav-link"%></li>
                <li class="nav_item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <%= current_user.name %><b class="caret"></b>
                    </a> 
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><%=link_to "Profile", current_user, class:"dropdown-item" %></li>
                            <li><%=link_to "Settings", edit_user_path(current_user), class:"dropdown-item" %></li>
                            <li class="divider"></li>
                            <li>
                                <%=link_to "Sign out", logout_path, method: :delete, class:"dropdown-item" %>
                            </li>
                        <% if current_user.is_admin? %> 
                            <li>
                                <%=link_to "Manage Catefories", admin_categories_path, class:"dropdown-item" %>
                            </li>
                            <li>
                                <%=link_to "Administer Users", admin_users_path, class:"dropdown-item" %>
                            </li>
                        <% end %>
                    </ul>
                </li>
              <%else%>
                <li class="nav-item">
                    <%= link_to "Signup", signup_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", login_path, class: "nav-link" %>
                </li>
              <%end%>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html><!--全てに共通させたいものはapplication.html.erbに書く-->
<html>
    <head>
        <title>ELearning</title><!--タブのタイトル-->
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Dosis|Source+Serif+Pro&display=swap" rel="stylesheet">
    </head>

    <body>
        <%= render 'layouts/header'%>
            <div>
                <%= yield %>
            </div>
        <%= render 'layouts/footer'%>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %><%#たくさんのオブジェクトのなかから何かエラーがないか探す%>
    <div class="alert alert-danger">
        <div><%#複数エラーがあったときはエラーメッセージを表示/ prohibited this action= このアクションは禁止されている%>
            <%= pluralize(object.errors.count,"error")%> prohibited this action:
        </div>
        <ul>
            <%object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <%end%>
        </ul>
    </div>
<% end %>